#! /bin/sh

pgrep -U blum sxhkd >/dev/null || sxhkd &

bspc monitor HDMI-0 -d I II III
bspc monitor DVI-I-0 -d IV V VI

bspc config border_width            3
bspc config window_gap              20

bspc config top_padding             20
bspc config bottom_padding          20
bspc config right_padding           20
bspc config left_padding            20

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config click_to_focus          none
bspc config focus_follows_pointer   true

bspc rule -a '*' state=tiled
bspc rule -a 'mpv' state=floating
bspc rule -a 'SshAskpass' state=floating
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
