#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ] ; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ] ; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ] ; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ] ; then
  xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if [ -d ~/.xinitrc.d ] ; then
  for f in ~/.xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 60 --output DVI-I-0 --mode 1920x1080 --rate 60 --right-of HDMI-0
setxkbmap -option "ctrl:nocaps"
xsetroot -cursor_name left_ptr
feh --no-fehbg --bg-scale ~/pix/forest.png
picom --daemon
#urxvtd --fork --opendisplay
dunst &
#dwm-status --daemon
pasystray &
nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings --load-config-only
#wacom_init 1


# start window manager
LOGDIR="$HOME/.log/i3"
[ -d "$LOGDIR" ] || mkdir "$LOGDIR"
#exec dwm >~/.dwm.log 2>&1
#exec bspwm >~/.bspwm.log 2>&1
#exec herbstluftwm >~/.herbstluftwm.log 2>&1
exec i3 >"$LOGDIR/i3.log" 2>&1
