#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ] ; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ] ; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ] ; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ] ; then
  xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if [ -d ~/.xinitrc.d ] ; then
  for f in ~/.xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 60 --output DVI-I-0 --mode 1920x1080 --rate 60 --right-of HDMI-0
setxkbmap -option "ctrl:nocaps"
xsetroot -cursor_name left_ptr
hsetroot -fill /usr/share/backgrounds/archlinux/archlinux-aftermath.jpg
compton --daemon
#dwm-status --daemon
pasystray &

xsetwacom --set "Wacom Intuos BT S Pen stylus" MapToOutput HEAD-1
xsetwacom --set "Wacom Intuos BT S Pen eraser" MapToOutput HEAD-1
xsetwacom --set "Wacom Intuos BT S Pen stylus" PressureCurve 25 0 100 75
xsetwacom --set "Wacom Intuos BT S Pen eraser" PressureCurve 25 0 100 75
xsetwacom --set "Wacom Intuos BT S Pen stylus" Area 0 0 15200 8550
xsetwacom --set "Wacom Intuos BT S Pen eraser" Area 0 0 15200 8550
xsetwacom --set "Wacom Intuos BT S Pen cursor" Area 0 0 15200 8550

xsetwacom --set "Wacom Intuos BT S Pad pad" Button 1 "key e"
xsetwacom --set "Wacom Intuos BT S Pad pad" Button 2 "key d"
xsetwacom --set "Wacom Intuos BT S Pad pad" Button 3 "key f"
xsetwacom --set "Wacom Intuos BT S Pad pad" Button 8 "key c"
xsetwacom --set "Wacom Intuos BT S Pen stylus" Button 2 "key z"
xsetwacom --set "Wacom Intuos BT S Pen stylus" Button 3 2

# start window manager
exec i3 2>&1 >~/.i3.log
#exec dwm 2>&1 >~/.dwm.log
