HISTFILE="$HOME/.histfile"
HISTSIZE=1000
SAVEHIST=1000
KEYTIMEOUT=10

export BROWSER='qutebrowser'
export EDITOR='nvim'
export VISUAL='nvim'
export SUDO_ASKPASS='/usr/lib/ssh/ssh-askpass'
export SUDO_EDITOR='nvim'
export LESS=' -Ri '
export LESSOPEN='|pygmentize -g %s'
export MANPAGER='less'
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

setopt autocd
setopt beep
setopt extendedglob
setopt inc_append_history
setopt nomatch
setopt notify
setopt share_history

zstyle :compinstall filename "$HOME/.zshrc"
zstyle ':completion:*' rehash true
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+l:|=* r:|=*'
autoload -Uz compinit promptinit
compinit
promptinit

bindkey -v
bindkey -M viins 'jk' vi-cmd-mode

zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char

prompt pure

alias c='cat'
alias ls='ls --color=auto'
alias l='lsd'
alias la='lsd -a'
alias ll='lsd -l'
alias lla='lsd -la'
alias q='exit'

alias Psyu='sudo pacman -Syu'
alias Psyy='sudo pacman -Syy'
alias Ps='sudo pacman -S'
alias Prsn='sudo pacman -Rsn'
alias Pu='sudo pacman -U'
alias Pss='pacman -Ss'
alias Psi='pacman -Si'
alias Pqi='pacman -Qi'
alias Pql='pacman -Ql'
alias Pqm='pacman -Qm'
alias Pqmq='pacman -Qmq'
alias Pqdt='pacman -Qdt'

# base16-shell
BASE16_SHELL="$HOME/.config/base16-shell"
BASE16_SHELL_SET_BACKGROUND="false"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
    eval "$("$BASE16_SHELL/profile_helper.sh")"

# command-not-found (pkgfile)
source /usr/share/doc/pkgfile/command-not-found.zsh

# neofetch
neofetch
